version: 2.1
executors:
  golang:
    docker:
      - image: circleci/golang:latest
jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run:
          name: build
          command: go build -o dist/httpwait ./src
      # - run:
      #     name: test
      #     command: go test ./src/httpwait/tests/ -test.v
  # publish:
  #   executor: golang
  #   steps:
  #     - checkout
  #     - run:
  #         name: test
  #         command: go test ./src/httpwait/tests/ -test.v
  #     - run:
  #         name: build
  #         command: |
  #           go get github.com/mitchellh/gox
  #           gox -ldflags "-w -s" -output "dist/${CIRCLE_PROJECT_REPONAME}_{{.OS}}_{{.Arch}}" ./src
  #     - run:
  #         name: "Publish Release on GitHub"
  #         command: |
  #           go get github.com/tcnksm/ghr
  #           ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./dist/
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      # - publish:
      #     context: github-publish
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^[0-9]+\.[0-9]+\.[0-9]+$/
